# Generated by Django 4.2.16 on 2024-12-06 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='ID_Administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.administrador'),
        ),
        migrations.AlterModelTable(
            name='administrador',
            table='administrador',
        ),
        migrations.AlterModelTable(
            name='encuesta',
            table='encuesta',
        ),
        migrations.AlterModelTable(
            name='encuestado',
            table='encuestado',
        ),
        migrations.AlterModelTable(
            name='establecimiento',
            table='establecimiento',
        ),
        migrations.AlterModelTable(
            name='log',
            table='log',
        ),
        migrations.AlterModelTable(
            name='pregunta',
            table='pregunta',
        ),
        migrations.AlterModelTable(
            name='respuesta',
            table='respuesta',
        ),
    ]
