# Generated by Django 4.2.16 on 2024-12-06 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_encuesta_id_administrador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='Contraseña',
        ),
        migrations.AlterField(
            model_name='administrador',
            name='ID_Establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.establecimiento'),
        ),
    ]
