# Generated by Django 4.2.16 on 2024-12-06 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_administrador_contraseña_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='ID_Administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.administrador'),
        ),
        migrations.AlterField(
            model_name='log',
            name='ID_Encuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.encuesta'),
        ),
        migrations.AlterField(
            model_name='log',
            name='ID_Encuestado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.encuestado'),
        ),
        migrations.AlterField(
            model_name='log',
            name='ID_Respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.respuesta'),
        ),
    ]
